package com.hyundai.web.entity;

// Generated Apr 8, 2016 8:44:28 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonView;
import com.hyundai.web.jsonview.Views;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	@JsonView(Views.Public.class)
	private long id;
	@JsonView(Views.Public.class)
	private String empName;
	@JsonView(Views.Public.class)
	private String empDesg;
	private Set jobs = new HashSet(0);

	public Employee() {
	}

	public Employee(long id) {
		this.id = id;
	}

	public Employee(long id, String empName, String empDesg, Set jobs) {
		this.id = id;
		this.empName = empName;
		this.empDesg = empDesg;
		this.jobs = jobs;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getEmpDesg() {
		return this.empDesg;
	}

	public void setEmpDesg(String empDesg) {
		this.empDesg = empDesg;
	}

	public Set getJobs() {
		return this.jobs;
	}

	public void setJobs(Set jobs) {
		this.jobs = jobs;
	}

}
