package com.hyundai.web.entity;

import com.fasterxml.jackson.annotation.JsonView;
import com.hyundai.web.jsonview.Views;

// Generated Apr 8, 2016 8:44:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * Jobline generated by hbm2java
 */
public class Jobline implements java.io.Serializable {

	@JsonView(Views.Public.class)
	private long id;
	private Job job;
	@JsonView(Views.Public.class)
	private Task task;

	public Jobline() {
	}

	public Jobline(long id) {
		this.id = id;
	}

	public Jobline(long id, Job job, Task task) {
		this.id = id;
		this.job = job;
		this.task = task;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

}
