package com.hyundai.web.entity;

// Generated Apr 8, 2016 8:44:28 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonView;
import com.hyundai.web.jsonview.Views;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private long id;
	@JsonView(Views.Public.class)
	private String taskName;
	@JsonView(Views.Public.class)
	private Set joblines = new HashSet(0);

	public Task() {
	}

	public Task(long id) {
		this.id = id;
	}

	public Task(long id, String taskName, Set joblines) {
		this.id = id;
		this.taskName = taskName;
		this.joblines = joblines;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public Set getJoblines() {
		return this.joblines;
	}

	public void setJoblines(Set joblines) {
		this.joblines = joblines;
	}

}
